### ISSUE TITLE
This is false. i use this DAILY on a project.

### ISSUE THREAD

**Issue by anxtyanxty** [c0deDemon/ascii.h#3]
This is false. i use this DAILY on a project.

_Originally posted by @c0deDemon in https://github.com/c0deDemon/ascii.h/issues/2#issuecomment-1197062796_

So you just make keyloggers or something? I don't see why else you would use this SLOW code.

**Comment by c0deDemon** [comment]
Bro that is not my fault that you find keylogger useful for this stuff. That actually show how you think which is actually pretty sad
