### ISSUE TITLE
Bro that is not my fault that you find keylogger useful for this stuff. That actually show how you think which is actually pretty sad

### ISSUE THREAD

**Issue by anxtyanxty** [c0deDemon/ascii.h#4]
Bro that is not my fault that you find keylogger useful for this stuff. That actually show how you think which is actually pretty sad

_Originally posted by @c0deDemon in https://github.com/c0deDemon/ascii.h/issues/3#issuecomment-1197509710_

Why would I even need this when the majority of it can be replaced with chars? Also, why else would you need to use this if you aren't writing keyloggers all day?

**Comment by c0deDemon** [comment]
so why comment on stuff you dont need. move along. do you comment on 20000 other stuff on github a day? i dnt understand?

As i said. i use this daily. especially over socket. Now once again and the last time. hop off my dick.
